import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/custom/layout/sidebar';
import {
   Calendar,
   Home,
   Inbox,
   Search,
   Settings,
   Newspaper,
   Pencil,
   SearchIcon,
} from 'lucide-react';
import { Toaster } from 'sonner';

// Menu items.
const items = [
   {
      title: 'All Posts',
      url: '/articles',
      icon: Newspaper,
   },
   {
      title: 'Add New',
      url: '/articles/new',
      icon: Pencil,
   },
   {
      title: 'Preview',
      url: '/preview',
      icon: SearchIcon,
   },
];

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <Toaster />
            <SidebarProvider>
               <AppSidebar items={items} title="XY APP" />
               <SidebarTrigger />
               {children}
            </SidebarProvider>
         </body>
      </html>
   );
}
